export const REQUEST_VISITS_PENDING = 'REQUEST_VISITS_PENDING'
export const REQUEST_VISITS_SUCCESS = 'REQUEST_VISITS_SUCCESS'
export const REQUEST_VISITS_FAILED = 'REQUEST_VISITS_FAILED'

export const SAVE_VISITS_EDITED_PENDING = 'SAVE_VISITS_EDITED_PENDING'
export const SAVE_VISITS_EDITED_SUCCESS = 'SAVE_VISITS_EDITED_SUCCESS'
export const SAVE_VISITS_EDITED_FAIL = 'SAVE_VISITS_EDITED_FAIL'

export const ADD_VISIT_PENDING = 'ADD_VISIT_PENDING'
export const ADD_VISIT_SUCCESS = 'ADD_VISIT_SUCCESS'
export const ADD_VISIT_FAIL = 'ADD_VISIT_FAIL'

export const CLONE_VISIT_PENDING = 'CLONE_VISIT_PENDING'
export const CLONE_VISIT_SUCCESS = 'CLONE_VISIT_SUCCESS'
export const CLONE_VISIT_FAIL = 'CLONE_VISIT_FAIL'

export const REMOVE_VISIT_PENDING = 'REMOVE_VISIT_PENDING'
export const REMOVE_VISIT_SUCCESS = 'REMOVE_VISIT_SUCCESS'
export const REMOVE_VISIT_FAIL = 'REMOVE_VISIT_FAIL'

