export const REQUEST_VISITS_PENDING = 'REQUEST_VISITS_PENDING'
export const REQUEST_VISITS_SUCCESS = 'REQUEST_VISITS_SUCCESS'
export const REQUEST_VISITS_FAILED = 'REQUEST_VISITS_FAILED'

export const SAVE_VISITS_EDITED_PENDING = 'SAVE_VISITS_EDITED_PENDING'
export const SAVE_VISITS_EDITED_SUCCESS = 'SAVE_VISITS_EDITED_SUCCESS'
export const SAVE_VISITS_EDITED_FAIL = 'SAVE_VISITS_EDITED_FAIL'